<?xml version="1.0" encoding="UTF-8"?>
<testsuites timestamp="2023-06-21T16:43:38.289" time="40.666" tests="15" skipped="0" failures="10" errors="1">
<testsuite name="test/testfiles/_retry_tests.jl" timestamp="2023-06-21T16:43:38.289" time="40.666" tests="15" skipped="0" failures="10" errors="1">
	<testcase name="Pass on second run" timestamp="2023-06-21T16:43:38.289" time="0.157" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="2476162"></property>
		<property name="dd_tags[perf.allocs]" value="40391"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.028837001"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.0029076239999999975"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:17">Captured logs for test setup "StatefulSetup" (dependency of "Pass on second run") at test/testfiles/_retry_tests.jl:1 on worker 78453
These are the test setup logs.
No Captured Logs for test item "Pass on second run" at test/testfiles/_retry_tests.jl:12 on worker 78453
Error in testset "Pass on second run" on worker 78453:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:17
  Expression: x
		</error>
	</testcase>
	<testcase name="Pass on second run" timestamp="2023-06-21T16:43:38.623" time="0.002" tests="1" skipped="0" failures="0" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="79494"></property>
		<property name="dd_tags[perf.allocs]" value="1227"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.0"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.0022935"></property>
		</properties>
	</testcase>
	<testcase name="Error, then Fail, then Pass" timestamp="2023-06-21T16:43:38.626" time="0.443" tests="1" skipped="0" failures="0" errors="1">
		<properties>
		<property name="dd_tags[perf.bytes]" value="72680426"></property>
		<property name="dd_tags[perf.allocs]" value="1352076"></property>
		<property name="dd_tags[perf.gctime]" value="0.004835375"></property>
		<property name="dd_tags[perf.compile_time]" value="0.370915293"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.06755041500000003"></property>
		</properties>
		<error message="Error during test at test/testfiles/_retry_tests.jl:26">Captured logs for test setup "StatefulSetup" (dependency of "Error, then Fail, then Pass") at test/testfiles/_retry_tests.jl:1 on worker 78453
These are the test setup logs.
Captured Logs for test item "Error, then Fail, then Pass" at test/testfiles/_retry_tests.jl:20 on worker 78453
These are the logs for run number: 1
Error in testset "Error, then Fail, then Pass" on worker 78453:
Error During Test at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:26
  Test threw exception
  Expression: not_defined_err
  UndefVarError: not_defined_err not defined
  Stacktrace:
   [1] macro expansion
     @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Test/src/Test.jl:464 [inlined]
   [2] top-level scope
     @ /repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:26
		</error>
	</testcase>
	<testcase name="Error, then Fail, then Pass" timestamp="2023-06-21T16:43:39.129" time="0.008" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="216419"></property>
		<property name="dd_tags[perf.allocs]" value="3704"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.005032125"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.0034412920000000003"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:28">Captured logs for test setup "StatefulSetup" (dependency of "Error, then Fail, then Pass") at test/testfiles/_retry_tests.jl:1 on worker 78453
These are the test setup logs.
Captured Logs for test item "Error, then Fail, then Pass" at test/testfiles/_retry_tests.jl:20 on worker 78453
These are the logs for run number: 2
Error in testset "Error, then Fail, then Pass" on worker 78453:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:28
  Expression: 2 + 2 == 5
   Evaluated: 4 == 5
		</error>
	</testcase>
	<testcase name="Error, then Fail, then Pass" timestamp="2023-06-21T16:43:39.189" time="0.003" tests="1" skipped="0" failures="0" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="103886"></property>
		<property name="dd_tags[perf.allocs]" value="1709"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="4.2e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.003226124"></property>
		</properties>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-21T16:43:39.192" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="76678"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="1.25e-7"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.0022902079999999997"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:37">Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 78453
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:34 on worker 78453
Error in testset "Has retries=4 and always fails" on worker 78453:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:37
  Expression: false
		</error>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-21T16:43:39.244" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="76678"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.0"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002130708"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:37">Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 78453
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:34 on worker 78453
Error in testset "Has retries=4 and always fails" on worker 78453:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:37
  Expression: false
		</error>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-21T16:43:39.295" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="76678"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="4.2e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002129916"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:37">Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 78453
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:34 on worker 78453
Error in testset "Has retries=4 and always fails" on worker 78453:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:37
  Expression: false
		</error>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-21T16:43:39.347" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="76678"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="1.66e-7"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002082001"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:37">Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 78453
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:34 on worker 78453
Error in testset "Has retries=4 and always fails" on worker 78453:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:37
  Expression: false
		</error>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-21T16:43:39.398" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="76678"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="8.3e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002061083"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:37">Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 78453
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:34 on worker 78453
Error in testset "Has retries=4 and always fails" on worker 78453:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:37
  Expression: false
		</error>
	</testcase>
	<testcase name="Has retries=1 and always fails" timestamp="2023-06-21T16:43:39.401" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="76678"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="4.2e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.0017605"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:43">Captured logs for test setup "StatefulSetup" (dependency of "Has retries=1 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 78453
These are the test setup logs.
No Captured Logs for test item "Has retries=1 and always fails" at test/testfiles/_retry_tests.jl:40 on worker 78453
Error in testset "Has retries=1 and always fails" on worker 78453:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:43
  Expression: false
		</error>
	</testcase>
	<testcase name="Has retries=1 and always fails" timestamp="2023-06-21T16:43:39.452" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="76678"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="8.4e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002114"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:43">Captured logs for test setup "StatefulSetup" (dependency of "Has retries=1 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 78453
These are the test setup logs.
No Captured Logs for test item "Has retries=1 and always fails" at test/testfiles/_retry_tests.jl:40 on worker 78453
Error in testset "Has retries=1 and always fails" on worker 78453:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:43
  Expression: false
		</error>
	</testcase>
	<testcase name="Has retries=1 and always fails" timestamp="2023-06-21T16:43:39.503" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="76678"></property>
		<property name="dd_tags[perf.allocs]" value="1171"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="4.2e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002125624"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:43">Captured logs for test setup "StatefulSetup" (dependency of "Has retries=1 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 78453
These are the test setup logs.
No Captured Logs for test item "Has retries=1 and always fails" at test/testfiles/_retry_tests.jl:40 on worker 78453
Error in testset "Has retries=1 and always fails" on worker 78453:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:43
  Expression: false
		</error>
	</testcase>
	<testcase name="Timeout always" timestamp="2023-06-21T16:43:39.506" time="20.011" tests="1" skipped="0" failures="0" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="487732"></property>
		<property name="dd_tags[perf.allocs]" value="8937"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.006507084"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="20.004509791"></property>
		</properties>
	</testcase>
	<testcase name="Timeout first, pass after" timestamp="2023-06-21T16:43:59.518" time="20.024" tests="1" skipped="0" failures="0" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="3374482"></property>
		<property name="dd_tags[perf.allocs]" value="59585"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.015807416"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="20.008099625"></property>
		</properties>
	</testcase>
</testsuite>
</testsuites>