<?xml version="1.0" encoding="UTF-8"?>
<testsuites timestamp="2023-06-21T12:12:17.063" time="60.635" tests="15" skipped="0" failures="10" errors="1">
<testsuite name="test/testfiles/_retry_tests.jl" timestamp="2023-06-21T12:12:17.063" time="60.635" tests="15" skipped="0" failures="10" errors="1">
	<testcase name="Pass on second run" timestamp="2023-06-21T12:12:17.063" time="0.117" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="2476514"></property>
		<property name="dd_tags[perf.allocs]" value="40394"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.029314042"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.0029177920000000024"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:15">Captured logs for test setup "StatefulSetup" (dependency of "Pass on second run") at test/testfiles/_retry_tests.jl:1 on worker 63296
These are the test setup logs.
No Captured Logs for test item "Pass on second run" at test/testfiles/_retry_tests.jl:10 on worker 63296
Error in testset "Pass on second run" on worker 63296:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:15
  Expression: x
		</error>
	</testcase>
	<testcase name="Pass on second run" timestamp="2023-06-21T12:12:17.367" time="0.003" tests="1" skipped="0" failures="0" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="80342"></property>
		<property name="dd_tags[perf.allocs]" value="1233"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="8.3e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.003417667"></property>
		</properties>
	</testcase>
	<testcase name="Error, then Fail, then Pass" timestamp="2023-06-21T12:12:17.375" time="0.44" tests="1" skipped="0" failures="0" errors="1">
		<properties>
		<property name="dd_tags[perf.bytes]" value="72681850"></property>
		<property name="dd_tags[perf.allocs]" value="1352094"></property>
		<property name="dd_tags[perf.gctime]" value="0.004799083"></property>
		<property name="dd_tags[perf.compile_time]" value="0.368289752"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.067274624"></property>
		</properties>
		<error message="Error during test at test/testfiles/_retry_tests.jl:24">Captured logs for test setup "StatefulSetup" (dependency of "Error, then Fail, then Pass") at test/testfiles/_retry_tests.jl:1 on worker 63296
These are the test setup logs.
Captured Logs for test item "Error, then Fail, then Pass" at test/testfiles/_retry_tests.jl:18 on worker 63296
These are the logs for run number: 1
Error in testset "Error, then Fail, then Pass" on worker 63296:
Error During Test at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:24
  Test threw exception
  Expression: not_defined_err
  UndefVarError: not_defined_err not defined
  Stacktrace:
   [1] macro expansion
     @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Test/src/Test.jl:464 [inlined]
   [2] top-level scope
     @ /repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:24
		</error>
	</testcase>
	<testcase name="Error, then Fail, then Pass" timestamp="2023-06-21T12:12:17.874" time="0.008" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="217267"></property>
		<property name="dd_tags[perf.allocs]" value="3710"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.005080292"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.0033554580000000004"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:26">Captured logs for test setup "StatefulSetup" (dependency of "Error, then Fail, then Pass") at test/testfiles/_retry_tests.jl:1 on worker 63296
These are the test setup logs.
Captured Logs for test item "Error, then Fail, then Pass" at test/testfiles/_retry_tests.jl:18 on worker 63296
These are the logs for run number: 2
Error in testset "Error, then Fail, then Pass" on worker 63296:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:26
  Expression: 2 + 2 == 5
   Evaluated: 4 == 5
		</error>
	</testcase>
	<testcase name="Error, then Fail, then Pass" timestamp="2023-06-21T12:12:17.935" time="0.003" tests="1" skipped="0" failures="0" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="104734"></property>
		<property name="dd_tags[perf.allocs]" value="1715"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.0"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.003234541"></property>
		</properties>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-21T12:12:17.938" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="77526"></property>
		<property name="dd_tags[perf.allocs]" value="1177"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="4.2e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002135833"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:35">Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 63296
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:32 on worker 63296
Error in testset "Has retries=4 and always fails" on worker 63296:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:35
  Expression: false
		</error>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-21T12:12:17.989" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="77526"></property>
		<property name="dd_tags[perf.allocs]" value="1177"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="2.5e-7"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.0021373330000000004"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:35">Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 63296
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:32 on worker 63296
Error in testset "Has retries=4 and always fails" on worker 63296:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:35
  Expression: false
		</error>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-21T12:12:18.039" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="77526"></property>
		<property name="dd_tags[perf.allocs]" value="1177"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.0"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.0020775"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:35">Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 63296
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:32 on worker 63296
Error in testset "Has retries=4 and always fails" on worker 63296:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:35
  Expression: false
		</error>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-21T12:12:18.089" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="77526"></property>
		<property name="dd_tags[perf.allocs]" value="1177"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="1.25e-7"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002139625"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:35">Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 63296
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:32 on worker 63296
Error in testset "Has retries=4 and always fails" on worker 63296:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:35
  Expression: false
		</error>
	</testcase>
	<testcase name="Has retries=4 and always fails" timestamp="2023-06-21T12:12:18.14" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="77526"></property>
		<property name="dd_tags[perf.allocs]" value="1177"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="4.2e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002051333"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:35">Captured logs for test setup "StatefulSetup" (dependency of "Has retries=4 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 63296
These are the test setup logs.
No Captured Logs for test item "Has retries=4 and always fails" at test/testfiles/_retry_tests.jl:32 on worker 63296
Error in testset "Has retries=4 and always fails" on worker 63296:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:35
  Expression: false
		</error>
	</testcase>
	<testcase name="Has retries=1 and always fails" timestamp="2023-06-21T12:12:18.142" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="77526"></property>
		<property name="dd_tags[perf.allocs]" value="1177"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.0"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.001823042"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:41">Captured logs for test setup "StatefulSetup" (dependency of "Has retries=1 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 63296
These are the test setup logs.
No Captured Logs for test item "Has retries=1 and always fails" at test/testfiles/_retry_tests.jl:38 on worker 63296
Error in testset "Has retries=1 and always fails" on worker 63296:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:41
  Expression: false
		</error>
	</testcase>
	<testcase name="Has retries=1 and always fails" timestamp="2023-06-21T12:12:18.192" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="77526"></property>
		<property name="dd_tags[perf.allocs]" value="1177"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="8.3e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.0020371259999999998"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:41">Captured logs for test setup "StatefulSetup" (dependency of "Has retries=1 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 63296
These are the test setup logs.
No Captured Logs for test item "Has retries=1 and always fails" at test/testfiles/_retry_tests.jl:38 on worker 63296
Error in testset "Has retries=1 and always fails" on worker 63296:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:41
  Expression: false
		</error>
	</testcase>
	<testcase name="Has retries=1 and always fails" timestamp="2023-06-21T12:12:18.243" time="0.002" tests="1" skipped="0" failures="1" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="77526"></property>
		<property name="dd_tags[perf.allocs]" value="1177"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="4.1e-8"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="0.002053251"></property>
		</properties>
		<error message="Test failed at test/testfiles/_retry_tests.jl:41">Captured logs for test setup "StatefulSetup" (dependency of "Has retries=1 and always fails") at test/testfiles/_retry_tests.jl:1 on worker 63296
These are the test setup logs.
No Captured Logs for test item "Has retries=1 and always fails" at test/testfiles/_retry_tests.jl:38 on worker 63296
Error in testset "Has retries=1 and always fails" on worker 63296:
Test Failed at /Users/nickr/repos/ReTestItems.jl/test/testfiles/_retry_tests.jl:41
  Expression: false
		</error>
	</testcase>
	<testcase name="Timeout always" timestamp="2023-06-21T12:12:18.246" time="30.016" tests="1" skipped="0" failures="0" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="509644"></property>
		<property name="dd_tags[perf.allocs]" value="9167"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.007062459"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="30.008791499"></property>
		</properties>
	</testcase>
	<testcase name="Timeout first, pass after" timestamp="2023-06-21T12:12:48.263" time="30.029" tests="1" skipped="0" failures="0" errors="0">
		<properties>
		<property name="dd_tags[perf.bytes]" value="3389242"></property>
		<property name="dd_tags[perf.allocs]" value="59714"></property>
		<property name="dd_tags[perf.gctime]" value="0.0"></property>
		<property name="dd_tags[perf.compile_time]" value="0.019414499"></property>
		<property name="dd_tags[perf.recompile_time]" value="0.0"></property>
		<property name="dd_tags[perf.eval_time]" value="30.00942096"></property>
		</properties>
	</testcase>
</testsuite>
</testsuites>